<script lang="ts">
	import SiteFooter from '$lib/site/SiteFooter.svelte';
	import { CHARITY, TIP_URL } from '$lib/site/money';
</script>

<svelte:head>
	<title>About — Pete Tong Is AI</title>
	<meta name="description" content="A fan-made tribute DJ desk with an AI imitation of Pete Tong's voice. Built for fun, not money." />
</svelte:head>

<div class="desk page">
	<div class="desk-header">
		<h1>About</h1>
		<p>Pete Tong Is AI</p>
	</div>

	<div class="page-body">
		<p>
			A fan-made tribute to Pete Tong and decades of dance music on the radio. Play with the desk, fire off a
			Jingle, have Pete introduce a track, and send a friend a Dedication. While the music plays, Pete
			back-announces what you've just heard.
		</p>

		<h2>The voice is AI, not Pete Tong</h2>
		<p>
			Every word "Pete" says here is generated by AI. It isn't him: he hasn't said, recorded or approved any of it,
			and he isn't involved with this site. The voice comes from
			<a href="https://github.com/resemble-ai/chatterbox" rel="noopener">Chatterbox</a>, an open-source
			text-to-speech model by Resemble AI, fine-tuned on short clips of his speech. Each clip carries an inaudible
			watermark that marks it as AI-generated, and the site labels it "AI voice, not Pete Tong" wherever it plays.
		</p>
		<p>
			What Pete reads in an Intro is typed by visitors, so an AI check screens it first. If a Dedication offends
			you, the link on its page removes it straight away, for everyone.
		</p>

		<h2>Built for fun, not money</h2>
		<p>
			No ads, no tracking, no accounts.
			{#if TIP_URL}Tips go towards the hosting costs (mostly the GPU that makes Pete's voice).{/if}
			{#if CHARITY}Donations to {CHARITY.name} go straight to the charity, never through this site.{/if}
		</p>

		<h2>Credits</h2>
		<ul>
			<li>Music plays through Spotify's embedded player.</li>
			<li>
				Track names for Track IDs come from <a href="https://musicbrainz.org" rel="noopener">MusicBrainz</a> and
				<a href="https://www.deezer.com" rel="noopener">Deezer</a>.
			</li>
			<li>Pete's voice: <a href="https://github.com/resemble-ai/chatterbox" rel="noopener">Chatterbox</a> by Resemble AI.</li>
		</ul>

		<h2>Get in touch</h2>
		<p>
			To reach whoever runs the site, use the contact form for the domain owner at the domain's registrar (look up
			petetongisai.com in a WHOIS search). That includes Pete Tong or anyone representing him who'd like something
			changed.
		</p>
		<p>See also: <a href="/privacy">Privacy</a>.</p>
	</div>

	<SiteFooter />
</div>
