<script lang="ts">
	import MoneyButtons from '$lib/site/MoneyButtons.svelte';
	import SiteFooter from '$lib/site/SiteFooter.svelte';
</script>

<svelte:head>
	<title>About — Pete Tong Is AI</title>
	<meta name="description" content="A fan-made tribute DJ desk with an AI imitation of Pete Tong's voice. Built for fun, not money." />
</svelte:head>

<div class="desk page">
	<div class="desk-header">
		<h1>About</h1>
		<p>Pete Tong Is AI</p>
	</div>

	<div class="page-body">
		<p>
			A fan-made tribute to Pete Tong and decades of dance music on the radio. Play with the desk, fire off a
			Jingle, have Pete introduce a track, and send a friend a Dedication. While the music plays, Pete
			back-announces what you've just heard.
		</p>

		<h2>The real Pete Tong is not AI</h2>
		<p>
			Let's be clear: the real Pete Tong is very much human. We've been listening to him since we were 18, back in the
			early '90s, and he is the don, the master, the legend. This site is a love letter, not an impersonation.
		</p>
		<p>
			Pete, if you're reading: should you ever fancy a special guest on your shows, we're ready to step in while you're
			on holiday, enjoying retirement or just juggling a busy schedule. We also offer dog sitting. We're not joking
			about the dog sitting.
		</p>

		<h2>The voice here is AI</h2>
		<p>
			Every word "Pete" says here is generated by AI. It isn't him: he hasn't said, recorded or approved any of it,
			and he isn't involved with this site. The voice comes from
			<a href="https://github.com/resemble-ai/chatterbox" rel="noopener">Chatterbox</a>, an open-source
			text-to-speech model by Resemble AI, fine-tuned on short clips of his speech. Each clip carries an inaudible
			watermark that marks it as AI-generated, and the site labels it "AI voice, not Pete Tong" wherever it plays.
		</p>
		<p>
			What Pete reads in an Intro is typed by visitors, so an AI check screens it first. If a Dedication offends
			you, the link on its page removes it straight away, for everyone.
		</p>

		<h2>Built for fun, not money</h2>
		<p>
			No ads, no tracking, no accounts. Use it the way dance music is meant to be enjoyed: joyful, inclusive and
			peaceful. Birthdays, best mates, first dances, Friday nights, and the friend who still owes you a tenner.
		</p>
		<p>
			If you feel this adventure is worthy, you can buy us a coffee towards the hosting costs (mostly the GPU that
			makes Pete's voice), or give to Shelter, the housing and homelessness charity. Donations to Shelter go straight
			to them, never through us, and this site isn't affiliated with them.
		</p>
		<MoneyButtons />

		<h2>Credits</h2>
		<ul>
			<li>Music plays through Spotify's or Mixcloud's embedded player.</li>
			<li>
				Track names for Track IDs come from <a href="https://musicbrainz.org" rel="noopener">MusicBrainz</a> and
				<a href="https://www.deezer.com" rel="noopener">Deezer</a>.
			</li>
			<li>Pete's voice: <a href="https://github.com/resemble-ai/chatterbox" rel="noopener">Chatterbox</a> by Resemble AI.</li>
		</ul>

		<h2>How it's made, and getting in touch</h2>
		<p>
			All of the site's code, design notes and decisions are open on
			<a href="https://github.com/kristerbone/petetongisai" rel="noopener">GitHub</a>. To reach whoever runs it,
			<a href="https://github.com/kristerbone/petetongisai/issues" rel="noopener">open an issue</a> there. That
			includes Pete Tong or anyone representing him who'd like something changed.
		</p>
		<p>See also: <a href="/privacy">Privacy</a>.</p>
	</div>

	<SiteFooter buttons={false} />
</div>
